### ISSUE TITLE
Allow developers to filter Tag Manager configuration

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1075]
GTM allows using data layers to customize which events and data are sent using "data layers" (see https://developers.google.com/tag-manager/devguide#datalayer).

Site Kit should, when rendering the JavaScript snippet for GTM, fire a filter `googlesitekit_gtm_data_layers` on an empty array, which plugin developers can use to add data layer objects to the configuration. If the array is not empty after running the filter, Site Kit should output it in a `script` tag right before the regular GTM snippet, assigned to a global `dataLayer` variable. The implementation could use `wp_json_encode` to provide the PHP data in a JS-compatible way, similar like the plugin currently does for the `googlesitekit_gtag_opt` filter.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should fire a `googlesitekit_gtm_data_layers` filter to allow developers providing data layer objects for the GTM snippet.
* If data layer objects are provided, they should be included in an additional script tag right before the GTM snippet.
* This change should only apply to the regular JS version - AMP and the no-JS fallback version should not be affected.

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz seeing as `dataLayer` isn't product-specific, I wonder if this filter should be more generic?

**Comment by felixarntz** [comment]
@aaemnnosttv Can you clarify a bit? Which other products does it apply to? My initial reaction is we should still scope the filter for GTM for now since that would be our intended use-case.

**Comment by aaemnnosttv** [comment]
Yeah, you can see other products mentioned here:
https://developers.google.com/gtagjs/devguide/snippet

That is technically under the `gtag.js` docs but it uses the same variable by default. 

[This document](https://developers.google.com/gtagjs/#google_tag_manager_or_gtagjs) also states:
> Tag Manager and gtag.js are built on the same infrastructure, and should work properly if deployed on the same page.

**Comment by felixarntz** [comment]
@aaemnnosttv Oh right. I'd say let's still keep this separate for now. Specifically, the data added here will be there from the start when GTM gets loaded, so I think clarifying this makes sense. Potentially we could add a similar filter for gtag in the future (let's not do this here though).

Maybe we should name the filter `googlesitekit_gtm_initial_data_layers` to clarify the intent?

**Comment by aaemnnosttv** [comment]
🤔 I'm not sure the alternate filter name is necessary. Interesting though that the code snippets shown for use with Tag Manager don't use the same `dataLayer = window.dataLayer || []` that gtag does (that there could already be an instance initialized).

On that note though, should the filter name perhaps use the singular form of layers? That seems to be how it's named in the docs.

I'll pick this up soon though now that all of my blocking questions have been resolved 👍

**Comment by felixarntz** [comment]
> 🤔 I'm not sure the alternate filter name is necessary. Interesting though that the code snippets shown for use with Tag Manager don't use the same `dataLayer = window.dataLayer || []` that gtag does (that there could already be an instance initialized).

Hmm, I still see similar logic for GTM, it only looks like it's written a different way, doing the same thing. Which snippets are you referring to?

> On that note though, should the filter name perhaps use the singular form of layers? That seems to be how it's named in the docs.

That makes sense, let's use the singular name.

These are all good questions, so I think we should hold off this one and move it back to ACs. I could dig a bit deeper and ask around for the recommended way to deal with data layers across multiple products, in a distributed ecosystem like a WP site.

**Comment by aaemnnosttv** [comment]
> Hmm, I still see similar logic for GTM, it only looks like it's written a different way, doing the same thing. Which snippets are you referring to?

Referring to the guide on how to use `dataLayer`:
https://developers.google.com/tag-manager/devguide#adding-data-layer-variables-to-a-page

The actual snippet for adding Tag Manager _does_ do this check when it initializes here:
![image](https://user-images.githubusercontent.com/1621608/73571753-f0cd3a00-4477-11ea-9835-19b5140691f3.png)

> That makes sense, let's use the singular name.

👍 

> These are all good questions, so I think we should hold off this one and move it back to ACs. I could dig a bit deeper and ask around for the recommended way to deal with data layers across multiple products, in a distributed ecosystem like a WP site.

👍

**Comment by felixarntz** [comment]
Modifying data layers for `gtm.js` can happen via injecting custom JavaScript into the page. #1862 will add action hooks `googlesitekit_init_tagmanager_tag` and `googlesitekit_init_tagmanager_tag_amp` that receive the respective Tag Manager container ID and can be used to add additional action hooks e.g. to inject such JavaScript.

Closing this issue as these hooks should satisfy the needs to modify Tag Manager behavior.
