### ISSUE TITLE
Update the splash screen's layout, copy, and graphics to match the Setup Flow Refresh Figma design.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#11333]
## Feature Description

Update the splash screen's layout, copy, and graphics to match the Setup Flow Refresh Figma design.

This does _not_ include the following:
- The “Recommended” badge below the Analytics checkbox.
- The info tooltip below the CTA, including its trigger icon and associated label.
- The Exit setup button.
- The progress indicator.

For reference, see the [splash screen design](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq/Setup-flow-refresh?node-id=1130-16651&t=ErUmKk1GVFCeQglT-0) (and its [wide viewport variant](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq/Setup-flow-refresh?node-id=2386-18059&m=dev)) on Figma, and the [Visual Changes section](https://docs.google.com/document/d/1CzPZhhsSlyfp718k2gSqMN-zHJdZ8Sr5eJcciZas2A0/edit?tab=t.778xo3dfqp9z#heading=h.y9zt00gt2dvq) in the Design Doc.

Update: Please note that as discussed in this [Figma thread](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq?node-id=1130-16651&m=dev#1442649391), we're updating the design to use the standard grey grid gutters around the content rather than having the background white to the viewport edge/WP admin menu. I.e. it will look something like this.

<img width="1527" height="1006" alt="Image" src="https://github.com/user-attachments/assets/8519887e-f6c8-4286-931c-0f24495a350e" />

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

-   The splash screen layout is updated to match the Figma design, barring the elements outlined in the Feature Description.
-   Copy changes are implemented according to the design. Some copy remains the same. The differences are outlined here, but please refer to the Figma design as the source of truth for the copy:
    -   Page title: _Let's get started!_
    -   Analytics checkbox:
        -   Title: _Get visitor insights by connecting Google Analytics as part of setup_
        -   Description: _To get better insights about your site, Site Kit will update your Analytics account, for example by enabling enhanced measurement. [Learn more]()_
            -   The target of the learn more link will be defined in a subsequent issue.
-   The graphics are updated according to the Figma design, with the following caveats:
    - At the time of writing there is an [open question](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq?node-id=2419-20492&m=dev#1408146991) about the size of the screenshot image that we should use. For this issue, we'll use the version linked in [this comment](https://github.com/google/site-kit-wp/issues/11333#issuecomment-3270071335). We may follow up with an issue to update it, depending on the outcome of the conversation in Figma.
    - It may not be readily apparent from the Figma design, but for viewports which are shorter than the screenshot image, the intention is to have the screenshot image clipped at the bottom edge of the viewport rather than allowing it to overflow and be scrollable.
-   The updated splash screen maintains all existing functionality while implementing the new visual design.
-   The splash screen remains responsive and accessible across different screen sizes and devices.
    -   Please note, we don't have explicit mobile designs in Figma, so we'll need to provide a best-effort implementation for mobile which can be refined later.
-   The changes are gated behind the `setupFlowRefresh` feature flag.

## Implementation Brief

- [x] Move [this piece of code](https://github.com/google/site-kit-wp/blob/5a0dc915c77018de2962472d1ec253312929ca21/assets/js/components/setup/SetupUsingProxyWithSignIn/Splash.js#L128-L215) into a new component that can be used as the **legacy splash component** (`LegacySplash`).
  - Pass the appropriate props to the component.

- [x] In `assets/js/components/setup/SetupUsingProxyWithSignIn/Splash.js`:
  - Use the `useFeature` hook to check whether `setupFlowRefresh` is enabled.
  - If `setupFlowRefresh` is disabled, render only the `LegacySplash` component.
  - If `setupFlowRefresh` is enabled, add the class `googlesitekit-splash` to the `Section` wrapper to target the elements within this container, else keep the currently used `googlesitekit-setup__splash` class.
  - The main container should be the `Grid`. Under the `Grid`, there should be a `Row` component with two `Cells`.
    - One cell should contain the left side of the layout, which includes the title and opt-in checkboxes. The children within this `Cell` should be made flex with a column direction (stacked vertically), gap should be `42px` as per figma design.
      - Use the `Typography` component to add the title, as shown in the Figma design. Match the styling as per figma design.
      - Add a parent wrapper element, like a `div`, to add the `Checkbox` and empty `div` as mentioned below.
        - Use the `Checkbox` component with `id` and `name` props as `googlesitekit-analytics-setup-opt-in`. Pass the `label` and `description` as per the Figma design.
          - The `Learn more` link will be handled in a subsequent issue.
          - Add the appropriate padding as per the Figma design.
        - Add an empty `div` with a height of `1px` and a width of `90%` with a background set to `$c-silver` as per Figma, to add the horizontal line. Add the top and margin as per figma.
      - Use the `Action` [component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/SetupUsingProxyWithSignIn/Actions.js) to render the `OptIn` for collecting data and the `Sign in with Google` CTA.
    - The other cell should contain the vector and the Site Kit post-setup screenshot.
      - Make the parent container relative so that the vector and screenshot image can be stacked.
      - Add the vector image (light green behind the screenshot) with the width and height matching the Figma design. Make its position `absolute`, and the `z-index` should be lower than the screenshot SVG.
      - Add the screenshot SVG component with the width and height matching the Figma design. Make its position `relative` (mainly to occupy the necessary space), and the `z-index` should be higher than the vector SVG.

- [x] Create a new file `_googlesitekit-splash.scss` in `assets/sass/components/setup/`. Add the new splash screen related styles in this file.
  - The right and bottom padding of the main grid container (`.mdc-layout-grid`) should be zero. Also, remove any margins so that the elements touch the edges as shown in the Figma design.

#### Responsive design considerations

We don't have a separate design for smaller viewports, but we can follow the existing pattern as follows.

- [x] The `Cell` containing the vector and the screenshot should appear at the top with an appropriate size. The current splash screen can be referenced for this.
- [x] The `Cell` with the analytics and data tracking opt-in options should appear below. The current splash screen can be referenced for this.

#### Wide viewport design

- [x] For the wide viewport, the maximum content width would be `1366px` as shown in figma design.
- [x] The background behind the main content would be greyed out like it is for the current splash screen to clearly separate out content frame from rest of the layout.
- [x] Use the SVG image given in [this comment](https://github.com/google/site-kit-wp/issues/11333#issuecomment-3270071335) for the wide viewport. Note that as the screenshot svg is positioned `relative` as mentioned in above point, it will automatically expand the container to add white space on it's left hand side.
  - The screenshot svg image should be clipped at the bottom edge of the viewport. The main container `googlesitekit-splash` and the wrapper container for the screenshot can be given `100vh` height. The container of the screenshot can be given overflow hidden.
  - Lazy loading for the svg image should be used in order to reduce the bundle size. Example of the lazy loading can be seen [here](https://github.com/google/site-kit-wp/blob/d54fc5b71f468b0fcd559d3502ebb2dd9a0ecf38/assets/js/components/KeyMetrics/GhostCardGreenSVG.js#L34).

### Test Coverage

- Add tests for `SetupUsingProxyWithSignIn` for when the `setupFlowRefresh` feature is enabled.
- Add stories for `SetupUsingProxyWithSignIn` for when `setupFlowRefresh` is enabled.

### QA Brief

1. Reset Site Kit so that splash screen is visible.

2. Enable `setupFlowRefresh` feature flag. Ensure that the new splash screen is visible. The designs should appear as per the figma design provided in the description.

3. Clicking on `Sign in with Google` button should redirect to OAuth screen to `/v3` service endpoint.

4. Also, test the [stories](https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in--default) added in storybook for different cases and viewports.

**Note:** We do not have the defined responsive behaviour in designs, so we don't expect the layout of the graphics to precisely match up with the Figma design. The responsive behaviour can be addressed in separate issues once we have that defined. In this issue, we will make sure that elements are looking fine and layout is looking fine in responsive layout.

## Changelog entry

* Implement the foundation for the forthcoming splash screen update.

**Comment by techanvil** [comment]
Hey @ankitrox, thanks for drafting this IB. It's heading the right direction, however there are some points to address.

- I had left a note in the IB on the [open question](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq?node-id=2419-20492#1408146991) about the size and format of the screenshot image, which needs to be resolved in order to complete the IB. It looks like you've missed this point, we do need to know this information as we may end up needing to use a bitmap rather than an SVG as discussed on the linked Figma thread.
- It also looks like you've missed the maximum width aspect of wide viewport design variant linked in the Feature Description.
-  Rather than keeping `googlesitekit-setup__splash` and adding `googlesitekit-setup__splash-refreshed` to the section's classnames, it would be cleaner to provide a new class, say `googlesitekit-splash`, which is rendered mutually exclusively with `googlesitekit-setup__splash`.
-  Please use the relevant design token or SCSS variable when mentioning a colour, rather than the hex code, e.g. `$c-utility-outline` rather than `#B8BDB9`.

**Comment by techanvil** [comment]
Hey @ankitrox, in order to unblock this issue, let's proceed with this SVG for the screenshot. We can follow up with an issue to update the screenshot as needs be.

![Image](https://github.com/user-attachments/assets/c4548c4e-2082-4ddc-950e-bf8d8dd94767)

**Comment by ankitrox** [comment]
Thank you @techanvil for reviewing the IB and adding the feedback. I've updated the IB to include the wide viewport section along with the content width and SVG instructions.

Also, updated the IB to include updates to class names and CSS variable.

**Comment by techanvil** [comment]
Hey @ankitrox, thanks for the IB update.

It's looking good, I think there are just two things left to address:

- It may not have been adequately covered in the Figma design/AC, but as discussed in this [thread](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq?node-id=1130-16651#1409739244) on Figma, we want to ensure the screenshot is clipped at the bottom edge of the viewport rather than overflow and be scrollable. I've updated the AC to make this more clear.
- It might be worth creating a new SCSS file, `assets/sass/components/setup/_googlesitekit-splash.scss`, to contain the new `.googlesitekit-splash` styles.

**Comment by techanvil** [comment]
Hey @ankitrox, one more point on the IB front. We should ensure we use [lazy loading](https://github.com/google/site-kit-wp/blob/d54fc5b71f468b0fcd559d3502ebb2dd9a0ecf38/assets/js/components/KeyMetrics/GhostCardGreenSVG.js#L30-L48) for the screenshot SVG, as @aaemnnosttv pointed out in this [Figma thread](https://www.figma.com/design/SquElvNorSTJOTV1I7oYAq?node-id=2419-20492#1408146991), in order to reduce the bundle size.

**Comment by ankitrox** [comment]
Thank you @techanvil for adding the pointers regarding wider viewport and CSS. I've amended these points in the IB.

**Comment by techanvil** [comment]
Thanks @ankitrox, that's great.

IB ✅

**Comment by techanvil** [comment]
Hey @ankitrox, I've merged this issue's PR, but please can you update the QAB as per this [comment](https://github.com/google/site-kit-wp/pull/11492#pullrequestreview-3314617412)?

**Comment by ankitrox** [comment]
Thanks @techanvil , updated the QAB and unassigned myself.

**Comment by techanvil** [comment]
Thanks Ankit!

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

I tested this and I have a number of observations, some of which might not necessarily need a fix but it will be great to confirm.

**ITEM 1:**
On the following 2 stories, the 'Sign in with Google' button is touching the lower side of the enclosure.
- https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-dashboard-sharing
- https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-staging-environment-warning

<Details>

<img width="1280" height="716" alt="Image" src="https://github.com/user-attachments/assets/2b8d7792-a6c5-4cec-a011-fe0a21a10b1b" />

<img width="1278" height="667" alt="Image" src="https://github.com/user-attachments/assets/08b8d611-70f4-41ee-9bf9-06bbd961a907" />

</Details>

________________________________________________________________________________


**ITEM 2:**
I understand we don't have mobile designs but currently, on mobile and tablets, the image will appear first and then only the text 'Let's get started!'

On some mobiles/scenarios, the user might not see the wordings and only the picture. I think it would be best to have the CTA at the top but that's subjective and probably needs a UX input here.

<Details>

<img width="537" height="507" alt="Image" src="https://github.com/user-attachments/assets/5debb166-a529-49b3-8378-69c8cec595f6" />

<img width="465" height="498" alt="Image" src="https://github.com/user-attachments/assets/c6fb9acd-57d7-400e-ba84-bc2199de433d" />

</Details>

________________________________________________________________________________


**ITEM 3:**
On mobile, the margin at the top is a lot more than the margin at the bottom.
Should we decrease the top and increase the bottom? 
That might also be dependent on our approach for ITEM 2. 

Photos attached for reference below:
<Details>

<img width="470" height="508" alt="Image" src="https://github.com/user-attachments/assets/8d8d0480-4a7b-49a0-b1ea-505a10aef13e" />

</Details>

________________________________________________________________________________


**ITEM 4:**

On tablet and mobile, the graphic image looks (and actually is) cut off on the left hand side and there is a huge white space, compared to desktop, where we extend it to the edge. Image is attached for reference.
- Should we extend the graphic wider and allow it to bleed to the edge?
- Also the text columns looks narrow. I am wondering maybe it's better if we enlarge it.

<Details>

<img width="600" height="496" alt="Image" src="https://github.com/user-attachments/assets/7c44ec90-b812-4777-b6e9-98baa4c65dac" />

</Details>

________________________________________________________________________________


**ITEM 5:**

One of the AC point is `Clicking on Sign in with Google button should redirect to OAuth screen to /v3 service endpoint.`
However, after I clicked it, it looks like routing to /v2. 

<Details>

<img width="986" height="297" alt="Image" src="https://github.com/user-attachments/assets/24046201-e0a1-4293-b80d-f14ceba7779b" />

</Details>

________________________________________________________________________________


**ITEM 6:**
Checkboxes have been implemented 40x 40.
Based on Figma, it's 32 x 32. 
Unless we are intentionally doing this to match design systems, maybe it's best to match Figma.
<Details>

<img width="1226" height="473" alt="Image" src="https://github.com/user-attachments/assets/dc2e502d-7b9c-4ac6-8f8a-ff8a4f446f3a" />

<img width="874" height="471" alt="Image" src="https://github.com/user-attachments/assets/74d2ba38-833a-4bdc-8a3b-13581da4b10f" />

</Details>

________________________________________________________________________________

**ITEM 7:**

The distance between the last text and the 'Sign in with Google' button on Figma is 42px.
We have implemented it as 32px.

<Details>
Figma:

<img width="734" height="533" alt="Image" src="https://github.com/user-attachments/assets/3ff823f1-71c1-437e-bf4c-6130da9b9977" />

Implementation:

<img width="1241" height="657" alt="Image" src="https://github.com/user-attachments/assets/18099570-145d-4060-9268-614cf2ef5947" />

</Details>

________________________________________________________________________________

**ITEM 8:**

The top of the graphic image should start below the text 'Let's get started!' on Figma.
In our implementation, it starts before that.

<Details>
Figma:

<img width="719" height="545" alt="Image" src="https://github.com/user-attachments/assets/5529d6c1-5dda-43a4-988c-8f8f0c0a05f7" />

Implementation:

<img width="1280" height="504" alt="Image" src="https://github.com/user-attachments/assets/77b232d9-b3c4-4afb-bfd1-8df04c268c8b" />

</Details>


________________________________________________________________________________

**ITEM 9:**

Not sure if this is intentional to align with other parts of the site but the CTA font family is implemented as 'Google Sans Text'.
On figma, it's 'Google Sans Display'

<Details>
Figma:

<img width="949" height="272" alt="Image" src="https://github.com/user-attachments/assets/2826637f-2f91-47ad-b636-42926ff93f0e" />

Implementation:

<img width="590" height="296" alt="Image" src="https://github.com/user-attachments/assets/723c65a0-4732-4cd9-a487-37f0362e712c" />

</Details>

**Comment by ankitrox** [comment]
@kelvinballoo Thank you for looking into this. Note that I've addressed few points in the follow-up PR. For other, I have added the response below, please go through it and let me know in case of any question.

**ITEM 1:**

I tried reproducing this and it only happens around ~300px height. As this is not a common resolution to have and we already have majority of the device covered including desktop, tablet mobile and wide viewport, I think we can proceed and if required, we can handle in separate issue for responsive one.

**ITEM 2:**

Same as above, because we do not have any mobile design and also for the current splash, we do not have the CTA at the top, so we can address in follow-up issue, if required.

**ITEM 3:**

Reduced the height


**ITEM 4:**

<img width="500"  alt="Image" src="https://github.com/user-attachments/assets/f0842d3f-c33b-4fa9-b0b7-1246d551603a" />

Again, this is same as that of how the current splash screen is spacing out on mobile devices. Please refer the attached screenshot. The green graphic in the background is actually like that, it's not getting cut from the right hand side. we can address in follow-up issue, if required.

**ITEM 5:**

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/27916b8b-8049-4fb6-9044-d81f6a77a8cc" />

It is `V3` of the Site Kit service side, the screenshot you added is referring to Google's auth screen. Please refer to attached screenshot.

**ITEM 6:**

We are using the standard checkbox component, I think we can keep it as is for now. Looping in @techanvil to confirm.

**ITEM 7:**

Fixed in follow-up PR.

**ITEM 8:**

Added 10px of additional margin from the top.

**ITEM 9:**

Updated in follow-up PR.

**Comment by techanvil** [comment]
Thanks @ankitrox.

> **ITEM 6:**
> 
> We are using the standard checkbox component, I think we can keep it as is for now. Looping in [@techanvil](https://github.com/techanvil) to confirm.

Yup, that's right - we should use the [standard checkbox component](https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/components-checkboxes--default). It is actually 40x40px where the source component is [defined in Figma](https://www.figma.com/design/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2-?node-id=553-1035&t=dmiU94qUn12fNHDy-0), so I'm not sure why it's 32x32px in the SFR design, but we can keep this as it is.

<img width="215" height="194" alt="Image" src="https://github.com/user-attachments/assets/e14c4e7f-842c-4b80-b5cb-c6db68caa904" />

I've also got some feedback on a few of the other points under discussion:

> **ITEM 1:**
> 
> I tried reproducing this and it only happens around ~300px height. As this is not a common resolution to have and we already have majority of the device covered including desktop, tablet mobile and wide viewport, I think we can proceed and if required, we can handle in separate issue for responsive one.

This actually occurs at any height in viewports between 961-1124px wide, so we should address it here. I'd suggest adding `padding-bottom` to `.googlesitekit-setup__content` for viewports with `min-width: $bp-desktop`.

<img width="979" height="1009" alt="Image" src="https://github.com/user-attachments/assets/10ec510e-abfd-4322-893d-7a6b360242c2" />

Incidentally, I've noticed a layout glitch at exactly 960px, the screenshot is displayed below the content - please can you fix this too?

<img width="979" height="1052" alt="Image" src="https://github.com/user-attachments/assets/403b7d6f-d5f1-4243-b769-fc7d241844e6" />

> **ITEM 2:**
> 
> Same as above, because we do not have any mobile design and also for the current splash, we do not have the CTA at the top, so we can address in follow-up issue, if required.

Agreed for the most part, however, Kelvin raised a valid point that the image is a bit on the tall side and the user might not see the title.

We can make an improvement now by reducing the `max-height` of the `.googlesitekit-setup__splash-graphic-screenshot` wrapper class for mobile viewports. I'd suggest a value of 230px, which will clip the graphic just below the traffic section's subtitle.

https://github.com/google/site-kit-wp/blob/5d7fb25ae1370d47b92df99bda9b3d91dce35f07/assets/sass/components/setup/_googlesitekit-splash.scss#L104-L106

<img width="848" height="656" alt="Image" src="https://github.com/user-attachments/assets/67dbf66e-7be2-45fb-b8b2-8704dfa24995" />

> **ITEM 4:**
> 
> ... The green graphic in the background is actually like that, it's not getting cut from the right hand side. we can address in follow-up issue, if required.

I've managed to extract an unclipped version of this SVG from a [copy](https://www.figma.com/design/48322BRn8VdrS6MyLTILQG/Setup-flow-refresh--Copy-3-?node-id=872-4191&p=f&t=SVkNVLhUvdNMOQz9-0) of the Figma design, so we can update this now too:

![Image](https://github.com/user-attachments/assets/6486c2ed-742d-4dcc-b5bc-705040e475a8)

**Comment by ankitrox** [comment]
Hi @techanvil 

Thanks for checking into the mentioned points. 

1. I have fixed the issue at 960px, now the image would appear first and then text. This is an existing issue in the current splash screen as well, so I updated that too.

2. Set the max-height of `230px` for mobile devices.

3. Updated the green SVG background. Please note that the rotation would be slightly different from what's shown in figma, but that is mainly because we have used different dimensions for the screenshot image, but overall its looking fine across different devices.

CC: @kelvinballoo

**Comment by techanvil** [comment]
Thanks @ankitrox!

The followup PR is merged, back to you @kelvinballoo for another pass.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Thanks @ankitrox , @techanvil . 
This is mostly good to go.

I just need you to check on ITEM 1, per my comment below @ankitrox .

**ITEM 1:** ⚠️ 
For https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-staging-environment-warning , I can still see a breakpoint where there is no padding at the bottom. Or am I looking at the wrong link for storybook?
E.g. 1031px
<Details>

<img width="729" height="456" alt="Image" src="https://github.com/user-attachments/assets/5b87e12f-0a12-435c-bde4-e71f50b24b49" />

</Details>

For https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-dashboard-sharing , at 971px also, it touches the bottom.

<Details>

<img width="654" height="415" alt="Image" src="https://github.com/user-attachments/assets/67f01e75-2ab7-4449-a841-aba6d866e0af" />

</Details>

__________________________________________

**ITEM 2:** ✅ 

Looking good on mobile. We can see the text and the image height is at 230px.

<Details>

<img width="544" height="602" alt="Image" src="https://github.com/user-attachments/assets/717cf0d0-b147-4f3a-9763-31c174f73b52" />

<img width="606" height="614" alt="Image" src="https://github.com/user-attachments/assets/edf9684a-e61a-4b23-b38f-8d4b3c8b4475" />

</Details>

__________________________________________

**ITEM 3:** ✅ 

Spacings are looking much better now.

<Details>

<img width="575" height="494" alt="Image" src="https://github.com/user-attachments/assets/3a9e6d9c-7661-43a1-81f5-ca458cad7b9d" />

</Details>

__________________________________________

**ITEM 4:** ✅ 

The clipping no longer appears on the right side. It happens on the bottom and looks much better than before.

<Details>

<img width="562" height="456" alt="Image" src="https://github.com/user-attachments/assets/af0ffbbd-a195-497a-96bf-0a6ce9eb641d" />

</Details>


__________________________________________

**ITEM 5:** ✅ 

Noted, that makes sense.
It goes to v3

<Details>

https://github.com/user-attachments/assets/cf1ae80e-e912-45c0-a6cb-899328863e08

</Details>

__________________________________________

**ITEM 6:** ✅ 
Noted, checkboxes should be remain as 40x 40.

__________________________________________

**ITEM 7:** ✅ 
Bottom margin is now 42px.

<Details>

<img width="1219" height="660" alt="Image" src="https://github.com/user-attachments/assets/70443a40-59b0-4e2b-a53d-c46f7822cb8e" />

</Details>


__________________________________________

**ITEM 8:** ✅ 

This is looking good now.

<Details>

<img width="1219" height="662" alt="Image" src="https://github.com/user-attachments/assets/c15272e2-b4a5-4598-a655-4e824af748fc" />

</Details>


__________________________________________

**ITEM 9:** ✅ 

Font is now Google Sans Display.

<Details>

<img width="543" height="319" alt="Image" src="https://github.com/user-attachments/assets/931c6f4b-239e-42a6-9000-acd53762153b" />

</Details>

**Comment by techanvil** [comment]
> **ITEM 1:** ⚠️ For https://storage.googleapis.com/site-kit-storybook/develop/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-staging-environment-warning , I can still see a breakpoint where there is no padding at the bottom. Or am I looking at the wrong link for storybook? E.g. 1031px

Thanks @kelvinballoo, good catch. We missed that in the followup PR, I've created another one to fix it.

You can check this on the [`main` version of Storybook](https://storage.googleapis.com/site-kit-storybook/main/index.html?path=/story/setup-using-proxy-with-sign-in-and-setupflowrefresh-enabled--default-with-staging-environment-warning), the fix will also be merged back to `develop` so it should be reflected there too.

**Comment by nfmohit** [comment]
The follow-up PR has been merged and this is now back in QA. Thanks folks!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil , @nfmohit 

This was verified good on develop and main storybook. Moving this ticket to approval as all other items have been rectified here: https://github.com/google/site-kit-wp/issues/11333#issuecomment-3402492324 

<Details>

<img width="587" height="432" alt="Image" src="https://github.com/user-attachments/assets/820e9c60-6a53-421e-8981-6e4663536237" />

<img width="996" height="779" alt="Image" src="https://github.com/user-attachments/assets/89651383-7f7c-4824-8e24-2fa62bd7a664" />

</Details>
