### ISSUE TITLE
Add `NoticeArea` component to the user engagement selection panel

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#11459]
## Feature Description

PUE Selection Panel component is implemented in #11424, as part of this issue we should implement the notice notification area component to display different notice depending on several conditions. 

As part of this issue, notices should be implemented together with the new wrapper component and then wired into the Selection Panel

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New notice area component is added to the user engagement `SelectionPanel` component implemented in #11424
* Said component is placed between the Header and Content sections of the `SelectionPanel`
* Said component should display notification when conditions are met:
    * In case GA was already connected and then disconnected, a dismissible warning notice is added notice is shown to both admin and view only users and matches [Figma design](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=756-8912&t=ujxAvgRSSZQfDqsb-0) for admins and [Figma design](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=756-12003&t=ujxAvgRSSZQfDqsb-0) for view only users
      * For admins it includes primary and secondary CTA, for view only users there is no CTA
      * Clicking on primary CTA starts the Analytics module setup
      * Clicking on secondary action dismisses notice
    * In case GA was never connected a feature suggestion notice will be added - shows for admins only and matches [Figma design](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=756-9782&t=ujxAvgRSSZQfDqsb-0)
      * Clicking on primary CTA starts the Analytics module setup
      * Clicking on secondary action dismisses notice
    * In case site level setting - `enabled` is toggled off warning notice is shown - for both admin view ([Figma design](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=710-7918&t=ujxAvgRSSZQfDqsb-0)) and view only users ([Figma design](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=710-8368&t=ujxAvgRSSZQfDqsb-0))
      * `Edit settings` CTA shows only for admin users, and clicking on `Edit settings` CTA redirects user to the Admin settings
* Each notice is showing appropriate text based on the scenario per Figma designs

## Implementation Brief

* [x] Add `assets/js/components/email-reporting/UserSettingsSelectionPanel/NoticeArea/AnalyticsDisconnectedNotice.js`
  * Reuse the notice and existing conditions for showing implemented in #11435
    * Include additional condition for notice to show - `isEmailReportingEnabled` selector from `CORE_SITE` should be `true`
  * Adjust the description and hide CTA for view only users
  * Design should match Figma files referenced in the AC
* [x] Add `assets/js/components/email-reporting/UserSettingsSelectionPanel/NoticeArea/SetupAnalyticsNotice.js` 
  * Use the same layout as in previous notice, with `type="new"` and learn more link using `$support_url = $this->authentication->get_proxy_support_link_url();`  `$doc_url = add_query_arg( 'doc', 'ga4', $support_url );` to the `ga4` doc key.
  * It should show only when user is admin and Analytics module is not connected and `isEmailReportingEnabled` is `true`
  * Match the design with [Figma](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-user-engagement?node-id=756-9782&t=jV1u2ZlAfOOaKA9g-0)
* [x] Add `assets/js/components/email-reporting/UserSettingsSelectionPanel/NoticeArea/EmailReportingDisabledNotice.js` 
  * Use the `Notice` component like before with `type="warning"`
  * Notice should not be dismissable
  * Adapt the description based on user capability - admin or view only user 
    * Admin [Figma](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=710-7918&t=ujxAvgRSSZQfDqsb-0)
    * View only users [Figma](https://www.figma.com/design/IsjMhBZHT5aMgBENleQoSQ/Proactive-notifications?node-id=710-8368&t=ujxAvgRSSZQfDqsb-0)
  * If user is admin, show the `Edit settings` CTA that navigates to the admin settings section, otherwise do not render the CTA
    * Use `getSiteKitAdminSettingsURL` selector for obtaining the URL for the admin settings
* [ ] Add `assets/js/components/email-reporting/UserSettingsSelectionPanel/NoticeArea/index.js`
  * Add a main wrapper with `div.googlesitekit-user-settings-selection__panel-notice-area` and render the previously added notices
* [x] Update `assets/js/components/email-reporting/UserSettingsSelectionPanel/PanelContent.js` - render the notice area wrapper after the `Header` component  

### Test Coverage

* Add tests for `assets/js/components/email-reporting/UserSettingsSelectionPanel/NoticeArea/index.js` verifying that only one notice is showing when conditions are met

## QA Brief

* Text the various scenarios (Analytics connected/disconnected, view-only dashboard, Email reporting disabled) to test the 4 new notices added as per the AC.
* KNOWN ISSUE: All notices currently follow the "desktop" single row design which is incorrect. These should be following mobile designs. However, this styling standardisation will be fixed in issue #9215 . Other than this layout, verify that all notices have the correct colours, text and CTA functionality.

## Changelog entry

* Add `NoticeArea` component to the user engagement selection panel.

**Comment by eugene-manuilov** [comment]
@zutigrm let's add references to corresponding Figma mockups to make it easier to find how exactly notices should look like.

**Comment by zutigrm** [comment]
Thanks @eugene-manuilov ,

Good point, IB updated

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. AC ✔️

**Comment by benbowler** [comment]
AC was approved so moving to IB for you.

**Comment by zutigrm** [comment]
@adamdunnage I added `Needs documentation` label, as we we probably want to cover the notice variations in the documentation and we will need a `Learn more` link destination - present in notice when analytics is disconnected

**Comment by aaemnnosttv** [comment]
Hey @zutigrm, I didn't see this in the design doc initially since it looks like it's only listed in the issue breakdown, so apologies for the late feedback here. I'm not sure we should add a notification area in the panel. The notifications API is mostly designed to manage queues of notifications in different areas that all compete for attention simultaneously on page load, and some ad-hoc. Since several modules, and core are competing for the same space, it's useful to avoid conflicts and manage priorities among the few dozen notifications we have. Since this wasn't elaborated on in the design, I'm wondering why we'd reach for this for only a few inline notices which all belong to the feature?

**Comment by zutigrm** [comment]
Hey @aaemnnosttv , we are not going to use Notifications API in this issue, the issue's AC and IB are calling for adding new wrapper component that includes 3 different notifications which are rendered  based on the GA4 status, feature being enabled, etc.

I renamed the title which could be a bit misleading

**Comment by jimmymadon** [comment]
@zutigrm The naming used within this issue heavily overlaps with our existing nomenclature that was introduced in the Banner Notifications Refactoring epic.

"Notice" is used for the 'design-only' component that renders a Site Kit "toast/alert" style notice in different colours based on the type.

"NoticeNotification" wraps a Notice and adds business logic specific to a Notification - i.e. uses an ID to automatically track GA events, adds callbacks for CTA/Dismiss clicks which tie into the queuing mechanism if needed, etc.

"Notification Area" puts notifications into an "area" group so that we know which of the current 3 areas (Header, Dashboard Top and Overlay) to automatically render them in using the API / queue mechanism.

In this issue, I see we are essentially rendering multiple different components, that will internally use `<Notice>` (not `NoticeNotification`,  in a new area but without using the automated area rendering mechanism. So perhaps we should call this wrapper component `NoticeArea` or simply, `Notices`. This will be name-spaced already inside the UserSettings selection panel anyway. Furthermore, maybe we should extract this component and put it inside `assets/js/components/SelectionPanel` so that in the future, we could render Notices in other types of Selection panels too? UPDATE: I can see that the wrapper here is actually rendering certain `Notice`s  conditionally that are relevant only for this User Engagement panel. But if there are any wrapper styles that are rendered, then those should be extracted into a common component within `assets/js/components/SelectionPanel` and conditional `Notice`s should be passed as children.

On a completely separate note, what `SettingsNotice` component are we referring to here? I looked at the IB of Issue #11435 but couldn't find a reference. We have removed the legacy `SettingsNotice` component completely and are now using `Notice` everywhere.

> instead of `SettingsNotice` use `Notice` component with type="warning"

**Comment by zutigrm** [comment]
Thanks @jimmymadon 

That's a good point, I renamed the wrapper component to the `NoticeArea` to dissociate from Notification API related naming more

> Furthermore, maybe we should extract this component and put it inside assets/js/components/SelectionPanel so that in the future, we could render Notices in other types of Selection panels too? UPDATE: I can see that the wrapper here is actually rendering certain Notices conditionally that are relevant only for this User Engagement panel. But if there are any wrapper styles that are rendered, then those should be extracted into a common component within

Yes correct, these are only PUE specific, so I didn't propose any shared component, as other panels do not handle this kind of layout/logic. If in the future if we get another selection panel that might also have similar notices inside, we can extract/share some part maybe, but in the meantime I would keep it scoped to the PUE.

> On a completely separate note, what SettingsNotice component are we referring to here? I looked at the IB of Issue https://github.com/google/site-kit-wp/issues/11435 but couldn't find a reference. We have removed the legacy SettingsNotice component completely and are now using Notice everywhere.

Ah good point, I proposed using `SettingsNotice` in the referenced issue, I removed that line there and here, thanks for the reminder.

**Comment by benbowler** [comment]
Thanks @zutigrm I made a few small tweaks and moving to EB.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Tested and here are a couple of feedback:

**ITEM 1:**
Can you confirm if the attached noticed is in the scope for this test?
If yes, I'd like to raise a point about the Learn more link which should have external icon as it links to an external link.

<Details>

<img width="1143" height="729" alt="Image" src="https://github.com/user-attachments/assets/b9cd76ef-1fad-4e58-a89b-b0fd7052eabf" />

</Details>

___________________________________________________________________________________________

**ITEM 2:**
For the analytics disconnected CTA, when I click on it, there is no 'Spinning animation' unlike other CTAs.
It would be a better experience to include it. 
Note that the behaviour is the same for **Email reporting disabled notice**.

<Details>

https://github.com/user-attachments/assets/509dcd2f-3fe4-4561-9500-0a11095d2782

</Details>

___________________________________________________________________________________________

**ITEM 3:**

In our implementation, we have the below text at the top of the panel.
"You can always deactivate this feature in Settings"
This text isn't there on Figma. 
That brings the question, should it be there or below the notice?

<Details>
Figma:

<img width="334" height="400" alt="Image" src="https://github.com/user-attachments/assets/2a824a4a-aa63-4219-baf9-5b1a7ba71cbd" />

Implementation:
<img width="536" height="435" alt="Image" src="https://github.com/user-attachments/assets/21e76528-7691-407a-a95a-64a517c8dae2" />

</Details>

___________________________________________________________________________________________

**ITEM 4:**

For the disabled scenario, 
- The text is 'This feature was disabled for all users. You can enable email reports subscriptions in settings'. Note that there is no period at the end. Since there is already a sentence, we should add a period at the end.
- The panel has the subscription plans below it (weekly, monthly, quarterly). By right these should not be there based on the figma. Same applies for view-only user.

<Details>

<img width="1142" height="561" alt="Image" src="https://github.com/user-attachments/assets/e57718e0-9cdb-4de3-8fad-6cea35c01a42" />

Figma:

<img width="304" height="409" alt="Image" src="https://github.com/user-attachments/assets/09736a7e-2acd-436a-a721-58150994fdad" />

</Details>



___________________________________________________________________________________________

**ITEM 5:**

For the disabled scenario, 
- We should add loading anitmation when we click on the CTA. Currently there is none.
- We should deeplink to the actual setting in the settings page rather than just going to the page.
<Details>

Current behaviour:

https://github.com/user-attachments/assets/d76fac09-a3f3-4191-aeaa-0027c01a4464

</Details>

**Comment by jimmymadon** [comment]
@kelvinballoo Thanks for thoroughly testing all of this.

ITEM 1: @sigal-teller has confirmed in [slack](https://fueled.slack.com/archives/C01CA828ZPZ/p1767598565620429) that this should not have the external icon if the link is pointing to our documentation. 

ITEM 2: I have created a follow up PR to add spinners to both, AnalyticsDisconnected and the ConnectAnalytics Notice CTAs.

ITEM 3: This is fine the way it is.

ITEM 4: I have fixed first part of adding period in the follow up PR. But for the second part, I have created a [separate issue](https://github.com/google/site-kit-wp/issues/12025) as I want to define this properly rather than extend this already delayed issue.

ITEM 5: Will define and fix this in the [above created issue](https://github.com/google/site-kit-wp/issues/12025).

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@jimmymadon for item 4 above you mentioned that you added the period in the follow-up PR, and that for the second part of the issue and (item 5) you created a separate ticket.
I checked and noticed that the period is still not added in the notice. Just wanted to confirm whether the missing period issue has already been fixed, or if it will be addressed under [#12025](https://github.com/google/site-kit-wp/issues/12025)

<details>

<img width="856" height="634" alt="Image" src="https://github.com/user-attachments/assets/b18d8952-8d63-40c2-904b-e8107c0d1c26" />

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that issue reported under [Item 2](https://github.com/google/site-kit-wp/issues/11459#issuecomment-3687985319) is resolve now.
- **Note** : Issue reported under Item 4 and Item 5 will get resolve through https://github.com/google/site-kit-wp/issues/12025

<details>

https://github.com/user-attachments/assets/0f23d16c-1df7-45af-b661-7666f601b245

https://github.com/user-attachments/assets/6c87560c-9423-4241-bb43-5a36750357fd

</details>
