### ISSUE TITLE
GTM: Existing container of same name should be preselected

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#361]
This is a follow up to #66: When setting up Tag Manager, with an already existing container that is named after your site (e.g. manually created before): When you choose "Setup new container", currently an error is displayed because a container of the same name already exists. When that error message displays, the existing container of that name should be automatically preselected, and the user should be informed about this selection.

The container should only be preselected, but the form should not be submitted automatically. The user must remain in full control.

This should also happen when the same scenario is encountered during a later change via the Tag Manager module settings panel.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a user chooses "Setup new container" and confirms, but then a container of that name already exists (there is already an error message displayed to indicate that), the existing container with this name should be selected.
* The error message should be expanded to indicate that the existing container of that name has been selected (e.g. "We've preselected the existing container for you.").
* This should be the case in both the module setup flow and the module settings panel.

## Implementation Brief

* If an API error is returned when trying to use a **new site container**, check the list of container names (`name`) to see if one matches the current blog name (`remove_accents( get_bloginfo( 'name' ) )` in PHP). If that exists, select that container from the list and let the user know that it's been pre-selected as a likely match.
* Set `this.state.selectedContainer` to a matching `container.name` if an API error is returned when using a `container.publicId` that is `0` in https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/assets/js/modules/tagmanager/setup.js

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr It would be great if you could specify the exact wording we should use to indicate that the existing container was selected (via the acceptance criteria).

**Comment by tofumatt** [comment]
I've added an implementation brief above for the current AC, though I wonder why the UX flow here requires a user wanting to setup a new tag only to be warned an existing one matches their site... shouldn't we _always_ pre-select a matching tag for the site if one exists? I'm not sure why we should confuse the user and force them to select wrong before we select the right option for them.

**Comment by felixarntz** [comment]
@tofumatt 
> I've added an implementation brief above for the current AC, though I wonder why the UX flow here requires a user wanting to setup a new tag only to be warned an existing one matches their site... shouldn't we _always_ pre-select a matching tag for the site if one exists? I'm not sure why we should confuse the user and force them to select wrong before we select the right option for them.

In principle yes, however we haven't implemented any matching for Tag Manager containers yet, which is something we're looking into (for example, related is #433). Let's focus in this issue to just help the user in the case of that specific error.

> The error message returned by the API: "Error: A container named '$SITE_URL' already exists in account $ACCOUNT_ID" should not appear if there is a matching container available for this site. Instead, it should use the message suggested above (e.g. "We've preselected the existing container for you").

Note that this should not appear _instead_ of the existing message. It should still be indicated to the user that the new container couldn't be created because of an existing one with the same name, but it should be added that said container is now preselected.

**Comment by tofumatt** [comment]
> Note that this should not appear "instead" of the existing message. It should still be indicated to the user that the new container couldn't be created because of an existing one with the same name, but it should be added that said container is now preselected.

I found the existing error message to be confusing, which is maybe why I wanted to hide it in this case. It says the container already belongs to an account (with only a numerical ID), which at first made me think the property belonged to another account. It was only by comparing that ID with my own Google account's Tag Manager ID that I noticed they matched. I suppose it's out-of-scope to change that message, but it wasn't very user-friendly.

I've updated the IB to say the message should appear additionally instead of in-place of the existing message.

**Comment by felixarntz** [comment]
@tofumatt 
> I found the existing error message to be confusing, which is maybe why I wanted to hide it in this case. It says the container already belongs to an account (with only a numerical ID), which at first made me think the property belonged to another account. It was only by comparing that ID with my own Google account's Tag Manager ID that I noticed they matched. I suppose it's out-of-scope to change that message, but it wasn't very user-friendly.

Ah, that makes sense. Potentially, we could say "A container named '$SITE_URL' already exists in your selected account. We've preselected that existing container for you." Thoughts? cc @marrrmarrr

**Comment by marrrmarrr** [comment]
SG to make it clear this is their account --> "exists in your selected account".

**Comment by felixarntz** [comment]
@tofumatt Can you please update the wording in the IB to match the above? Once that's changed, you can consider the IB approved 🙂

**Comment by tofumatt** [comment]
I just realised that error comes back from the API and is likely translated, so I first need to verify there's an available error code to create the "exists in your selected account" message for extra context.

If not this string would need to be updated on the server (which would actually be better, but I don't know where to file that and suspect it's a broader API issue 😅).

**Comment by tofumatt** [comment]
Actually, I don't think we should update the IB to handle that error; checking the HTTP response it's not very specific about the error, so I don't think we can safely change/add to this message without introducing false positives:

<img width="699" alt="Screenshot 2019-09-05 15 42 59" src="https://user-images.githubusercontent.com/90871/64352536-21599680-cff4-11e9-90bc-297d46f69ded.png">

**Comment by felixarntz** [comment]
@tofumatt So there's no error code at all returned by the API here, or any other piece of data we might get from that it's _that_ error?

**Comment by tofumatt** [comment]
The error code (`"badRequest"`) matches the HTTP status code (400 Bad Request), which isn't really specific. That code could mean any error made by the client for that request—in this case we are making a bad request because #433 isn't implemented.

Info on the errors is here: https://developers.google.com/tag-manager/api/v1/errors, but there isn't a list of more specific error codes and their cause. It also explicitly warns:

> The description could change at any time so applications should not depend on the actual description text.

so as I expected; we shouldn't just check the text.

This should be "won't fix"'d and focus should move to #433. If #433 is done, we should pick the tag for the current site (and not allow a user to create a new tag for the current site if a matching one already exists). The API response is legitimate because we aren't doing #433.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
Sorry, I should have updated the IB as well after leaving my comment above—I don't think this is an issue that should be addressed and is better solved by #433. Because the API response isn't sufficient to determine _what_ the error is, we shouldn't be selecting an option based on the API error.

Instead we should be preselecting an not presenting users with the possibility to hit this error by default.

**Comment by felixarntz** [comment]
@tofumatt There is still a part to this that we should fix. We shouldn't modify the error message from the API in any way, but, as the ACs state, preselect the container then and append to the error message that the container has been preselected for the user.

This issue is still valid and needs to be resolved here. The existing tag detection in #433 deals with code snippets already present in the website (e.g. from another plugin) and thus is unrelated.

**Comment by tofumatt** [comment]
Oh, whoops, I misunderstood the word "snippet" in the other issue and for some reason read it as a containers/property. 😅 When I saw:

> Let's focus in this issue to just help the user in the case of that specific error.

I think I misunderstood this issue as being about the error encountered because we weren't preselecting. I'll revisit this IB and look for the APIs we should be using to match the current site with the available GTM containers/properties.

**Comment by tofumatt** [comment]
I see what's up and why I was confused about this issue: one can't accurately determine a tag that matches the current site setup but it's what I was trying to find.

I would expect to pre-select a tag based on `domainName` in the [Tag Manager API response for the available containers](https://developers.google.com/tag-manager/api/v1/reference/accounts/containers#resource). But even after I setup a site using Tag Manager and visit the site—the site doesn't seem to have a list of domains registered with it.

I created a new site to test this, and after registering it with Tag Manager, I see this in the response:

<img width="358" alt="Screenshot 2019-09-26 22 25 09" src="https://user-images.githubusercontent.com/90871/65726393-df7cb700-e0ac-11e9-9c48-8b59cf00b9f8.png">

Using the site's _name_ seems unreliable. We use the blog's name (https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/includes/Modules/TagManager.php#L457) as the container name when creating a new one, so we _can_ select an existing tag based on the name. But if the name of the site has changed in either place we can't pre-select or accurately match a tag from what I understand.

-----

I've updated the IB, so if there's an API error and we have a tag that matches the name of the blog, to pre-select it. But I think that's problematic: the names can be changed on either end and aren't guaranteed to be matching properties, so I imagine this approach could lead to subtle bugs in the future, where a name that matches is selected even if it's not the right one. 🤷🏻‍♂️

**Comment by felixarntz** [comment]
> I've updated the IB, so if there's an API error and we have a tag that matches the name of the blog, to pre-select it. But I think that's problematic: the names can be changed on either end and aren't guaranteed to be matching properties, so I imagine this approach could lead to subtle bugs in the future, where a name that matches is selected even if it's not the right one.

The matching should only happen in the specific case where we just tried to create a new container. With that container, we know the exact name, since we specified it in the request, and if there already is a container of that name, we should be able to reliably match that.

In other words, I'd agree with that sentiment if we generally tried to match containers, but if it is just for this specific scenario, I think we're good.

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz I'm moving this back to IB since the current one is no longer up to date with the latest state of the component. It is now possible to create a container for both web and amp usage contexts in the same request which complicates this a bit more.

**Comment by aaemnnosttv** [comment]
It doesn't make sense to do this one before #1386 so I'm making this a prerequisite.

**Comment by felixarntz** [comment]
Closing this as there has been valid pushback here and it's not a huge issue either way. We can revisit if this comes up again as a concern.
