### ISSUE TITLE
Update AdSense account state detection logic based on new API capabilities

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5052]
Based on the recently released new AdSense API capabilities and the [corresponding enhancements to the design doc](https://docs.google.com/document/d/1vNpMW4iED2scWOjpF8SKGoM8z6GUjX-WbhMpmAKeieo/edit#heading=h.dvwukljp9z7x), we need to use the new `account.state` and `client.state` fields to determine the overall account status, instead of just using `account.pendingTasks`. This is essentially a follow-up to #4759.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Instead of checking for the AdSense account's `pendingTasks` value (see #4759 for background), the plugin should check the following:
    * Check: Is the account's `state` field set to "NEEDS_ATTENTION"?
        * If yes, set the Site Kit account status to `ACCOUNT_STATUS_NEEDS_ATTENTION`. Then display the `SetupAccountPendingTasks` component as before.
        * If not, check: Is the client's `state` field set to "REQUIRES_REVIEW" or "GETTING_READY"?
            * If yes, set the Site Kit account status to either `ACCOUNT_STATUS_CLIENT_REQUIRES_REVIEW` or `ACCOUNT_STATUS_CLIENT_GETTING_READY`, based on the value. Then display the `SetupAccountPendingTasks` (same as above!) here as well. (In other words, only the internal status stored should be different, but the UI the user sees should be the same for all of the above scenarios.)
            * If not, proceed (basically this means the account is `ACCOUNT_STATUS_READY`).
* Any Storybook mock data should be updated accordingly, i.e. add corresponding `state` fields to the mock data etc.

See [the new account state documentation](https://developers.google.com/adsense/management/reference/rest/v2/accounts#State) and [new client state documentation](https://developers.google.com/adsense/management/reference/rest/v2/accounts.adclients#State) for background on the possible values.

## Implementation Brief
* Using `assets/js/modules/adsense/components/setup/v2/SetupAccount.js`,
	* Get the `state` property from `account`.
	* In the `useEffect` hook, 
		* update the condition where we check for the length of `site.pendingTasks` to check if `state` is `NEEDS_ATTENTION`. The code where we set the account status to `ACCOUNT_STATUS_NEEDS_ATTENTION` should already be there, from https://github.com/google/site-kit-wp/issues/5051
		* add another check for `state` to see whether it's equal `REQUIRES_REVIEW` or `GETTING_READY` (and not `NEEDS_ATTENTION`).
			* If it's `REQUIRES_REVIEW`, set the account status to `ACCOUNT_STATUS_CLIENT_REQUIRES_REVIEW`
			* If it's `GETTING_READY`, set the account status to `ACCOUNT_STATUS_CLIENT_GETTING_READY`
	* Update the condition to render the `SetupAccountPendingTasks` component if `state` is one of `REQUIRES_REVIEW`, `GETTING_READY`, `NEEDS_ATTENTION`.
* Update `assets/js/modules/adsense/datastore/__fixtures__/accounts.json` and `assets/js/modules/adsense/datastore/__fixtures__/clients.json` to add new `state` field.

### Test Coverage
* No new tests to be added.

## QA Brief
* Ensure the stories under AdSense -> Components -> Setup -> v2 -> SetupMain render correctly without error.
* QA performed during code review: the stories did not change content in this PR. This can be QA'd by comparing the stories from a commit before this change (eg. 361519447240f67a8871d150c9be613a6786bd2b) with `develop`'s stories for AdSense -> Components -> Setup -> v2 -> SetupMain and ensuring they don't differ in output.

## Changelog entry

* Update AdSense V2 state detection logic with new API return values.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by felixarntz** [comment]
### QA ❌ 

The current implementation does not satisfy the ACs, as follows:
* The current implementation somehow compares the account's `state` to values that are our internal _site_ statuses. Please review the [the new account state documentation](https://developers.google.com/adsense/management/reference/rest/v2/accounts#State) and [new client state documentation](https://developers.google.com/adsense/management/reference/rest/v2/accounts.adclients#State) and the ACs more precisely to follow the logic defined there.
* The current implementation looks at the account's `state` field to set `ACCOUNT_STATUS_CLIENT_REQUIRES_REVIEW` and `ACCOUNT_STATUS_CLIENT_GETTING_READY`. It needs to look at **the client's `state` field** though to be able to determine these states correctly. The account's `state` field can only be used to set `ACCOUNT_STATUS_NEEDS_ATTENTION`.

The problems here are already present in the IB, so please take another look at the ACs to revise.

cc @asvinb @tofumatt @eugene-manuilov

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@asvinb when I click on 'Account: Pending Tasks' component, an error appears in the console.  

```
vendors~main.49d50365.iframe.bundle.js:2 Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableSpread (vendors~main.49d50365.iframe.bundle.js:2:2863142)
    at _toConsumableArray (vendors~main.49d50365.iframe.bundle.js:2:10574)
    at reducerCallback (main.5e9d8645.iframe.bundle.js:1:1169034)
    at reducer (main.5e9d8645.iframe.bundle.js:1:1579273)
    at main.5e9d8645.iframe.bundle.js:1:2256551
    at Array.reduce (<anonymous>)
    at main.5e9d8645.iframe.bundle.js:1:2256509
    at main.5e9d8645.iframe.bundle.js:1:2256551
    at Array.reduce (<anonymous>)
    at Object.root (main.5e9d8645.iframe.bundle.js:1:2256509)
```

![image](https://user-images.githubusercontent.com/73545194/164235661-60d490f4-83f1-4fe7-bb33-ed150d99421e.png)

**Comment by asvinb** [comment]
@wpdarren From what I've found is that the console error you're seeing is not related to the changes in the current ticket. Since we have https://github.com/google/site-kit-wp/issues/5106 to fix some logic issues, I suggest we instead check if the console errors are gone when the ticket is done. What do you think @aaemnnosttv ?

**Comment by aaemnnosttv** [comment]
@asvinb @wpdarren this is an error which is unique to Storybook environment and does not appear to be related to the changes here.

The `getURLChannels` selector is triggering a fetch from its resolver which is unmocked, so it's getting the default empty object as the response instead of an array. This is what's raising the error when the response is attempted to be spread into the new array.

@asvinb I'm not sure 5106 is the right place to fix this, as that issue is about fixing logic rather than UI. The problem here is more about story setup so this should be addressed in #4763 as part of the implementation for `SetupAccountPendingTasks`.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Ensured the stories under AdSense -> Components -> Setup -> v2 -> SetupMain render correctly without error.

As noted above, all of the stories load without error other than 'Account: Pending Tasks' component. As Evan mentioned this appears to be outside of this ticket.

**Comment by felixarntz** [comment]
### Approval ❌ 

The follow-up PR #5109 still hasn't correctly addressed what I've previously pointed out - it still does not look at the client as outlined in https://github.com/google/site-kit-wp/issues/5052#issuecomment-1101907230. Please review my detailed comments in https://github.com/google/site-kit-wp/pull/5109#pullrequestreview-952244429.

Let me know if you have any follow-up questions, this will need another round of fixes. I'm happy to assist or jump on a call, but we need to make sure to work more precisely here - account, site, and client are all different things.
