### ISSUE TITLE
Update settings validation and submission in Analytics

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6742]
## Feature Description

The `analytics` `submitChanges()` function should be updated to not allow creating a new UA property and profile, i.e. if the selected property is `property_create` or `profile_create`, they shouldn't be used to create new entities if the `ga4Reporting` feature flag is enabled.

The `analytics` `validateCanSubmitChanges()` function applies validation rules for Analytics settings, and is implemented through the `canSubmitChanges()` selector. This should be updated such that if the `ga4Reporting` feature flag is enabled, it doesn't require a UA property and profile to be selected (as they're optional once GA4 Reporting is enabled), but still require selecting/creating a GA4 property and web data stream.

[Here](https://docs.google.com/document/d/1b7kb9nBcF2javvj1VPPjBKiZlxgZNMzGygmY7WHcQoQ/edit?resourcekey=0-euqk7Ji7ErVA2UPVTz93JQ#heading=h.fmn1iz93ivdl) is the relevant section in the one-pager. [This](https://github.com/google/site-kit-wp/pull/6729/commits/330bf5568964ebeaf5f5aa89e6110f2179384cbf) and [this](https://github.com/google/site-kit-wp/pull/6729/commits/5625d62840d28834a8c3ec9e1e9ee7ba46126ba3) are the relevant sections in our PoC.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If the `ga4Reporting` feature flag is enabled:
  - The `analytics` `submitChanges()` function should be updated to not allow creating a new UA property and profile.
  - The `analytics` `validateCanSubmitChanges()` function should be updated to no longer require a UA property and profile, but still require a GA4 property and web data stream.

## Implementation Brief

* In `assets/js/modules/analytics/datastore/settings.js`, update the `submitChanges` function with the following:
  * Check if the `ga4Reporting` feature flag is enabled using the `isFeatureEnabled` function.
    * If it is not enabled AND the selected `propertyID` is `property_create`, execute the UA property creation logic. I.e., add the `ga4Reporting` check to the existing condition here:
    https://github.com/google/site-kit-wp/blob/c2bdc74c963870dbba8510727b995979f6aa2837/assets/js/modules/analytics/datastore/settings.js#L93-L109
    * If it is not enabled AND the selected `profileID` is `profile_create`, execute the UA profile creation logic. I.e., add the `ga4Reporting` check to the existing condition here:
    https://github.com/google/site-kit-wp/blob/c2bdc74c963870dbba8510727b995979f6aa2837/assets/js/modules/analytics/datastore/settings.js#L112-L127
* Update the `validateCanSubmitChanges` function with the following:
  * Check if the `ga4Reporting` feature flag is enabled using the `isFeatureEnabled` function.
    * If it is not enabled, execute the following validations:
      * `isValidPropertySelection( getPropertyID() )`
      * `isValidProfileSelection( getProfileID() )`
      * `isValidProfileName( profileName )`
      * `! isValidPropertyID( getPropertyID() ) || isValidInternalWebPropertyID( getInternalWebPropertyID() )`

Note: The `getPropertyID` and `getWebDataStreamID` of `analytics-4` validations will be triggered by the `__dangerousCanSubmitChanges` selector call.

### Test Coverage

* Update `analytics` and `analytics-4` - `submitChanges` tests to check that the `ga4Reporting` feature flag is enabled and that the correct selectors are called.
* The correct selectors are called when the feature flag is not enabled.

## QA Brief

In the Analytics setup and settings form UI, ensure the following:
* When the `ga4Reporting` feature flag is enabled:
  * The `propertyID` and `profileID` selectors should not be required. Instead, set the UA `Property` to `Set up a new property`.
  * The Profile (`View`) to be `Set up a new view`.
  * `View Name` should be empty.
  * Ensure the `Configure Analytics` button is enabled and the form can be submitted.
  * Ensure the `create-property` and `create-profile` of the `analytics` module API calls are not made.
 
<img width="1002" alt="Screenshot 2023-03-27 at 6 11 48 PM" src="https://user-images.githubusercontent.com/24408261/227944761-1d6b5c99-0405-48bf-ab23-99df056fb88f.png">

* When the `ga4Reporting` feature flag is disabled, it should work as it currently does.

## Changelog entry

* Update settings validation and requirements when `ga4Reporting` is enabled.

**Comment by tofumatt** [comment]
ACs are good 👍🏻

**Comment by eugene-manuilov** [comment]
> If the feature flag is enabled, validate the following selectors from the `modules/analytics-4` datastore:
> * `isValidPropertySelection( getPropertyID() )`
> * `isValidWebDataStreamSelection( getWebDataStreamID() )`

@hussain-t, I think this is not needed because we already check it in the `analytics-4` module that is triggered by the `__dangerousCanSubmitChanges` selector call from the `analytics-4` module in the `validateCanSubmitChanges` function.

**Comment by hussain-t** [comment]
Thanks, @eugene-manuilov. I have updated the IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
@wpdarren, you see those errors because the UA property was created without the necessary fields like propertyID and profile. This is fixed in #6746. The UA widgets won't be rendered, and the API calls for the UA endpoints won't be made if the `ga4Reporting` feature flag is enabled and the dashboard view is GA4.

**Comment by wpdarren** [comment]
@hussain-t okay, thank you for clarifying that. Please note, it would be good if you can include any of this type of expected behaviour in the QAB, but no worries!  👍  

I do have another question though. 

> The UA widgets won't be rendered, and the API calls for the UA endpoints won't be made if the ga4Reporting feature flag is enabled and the dashboard view is GA4.

On this test site I have GA4Reporting feature flag enabled and I am on the GA4 dashboard view (selected the CTA on the banner)  Sp, should I still see these errors on the dashboard? If yes, that's fine, but wanted to double check.  

My concern wi this type of scenario is that it is important we make sure these errors are fixed when 6746 is tested, so, I will include a comment on that ticket of my findings so we know to include this in testing.  Would you agree, or, do you feel this will be picked up as part of testing that ticket in the QAB?

**Comment by hussain-t** [comment]
>Please note, it would be good if you can include any of this type of expected behaviour in the QAB, but no worries! 👍

Thanks, @wpdarren 👍 

>On this test site I have GA4Reporting feature flag enabled and I am on the GA4 dashboard view (selected the CTA on the banner) So, should I still see these errors on the dashboard? If yes, that's fine, but wanted to double check.

Yes, until #6746 is merged.

>My concern with this type of scenario is that it is important we make sure these errors are fixed when 6746 is tested, so, I will include a comment on that ticket of my findings so we know to include this in testing. Would you agree, or, do you feel this will be picked up as part of testing that ticket in the QAB?

Both aren't tightly coupled with each other. This ticket only removes the UA setup validations. #6746 generally prevents UA API calls if the `ga4Reporting` feature flag is enabled and the dashboard view is GA4. Does that make sense?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Configure Analytics button is enabled and the form can be submitted.
- The `create-property` and `create-profile` of the analytics module API calls are not made.

**Note:** When following the QAB steps, there are errors on the dashboard, console and network tabs. This is expected until 6746 is merged. We will make sure that this is no longer an issue in that ticket when it's in QA.
