### ISSUE TITLE
Additional permissions popup appears over the 'Site Kit Needs Permission' notice

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6764]
## Bug Description

This was discovered in Bug Bash by @wpdarren and confirmed by @jamesozzie, @mohitwp, and @techanvil.

## Steps to reproduce

1. I set up Site Kit with Analytics, but with the GTEsupport feature flag disabled.  This is for a new website using the InstaWP service. 
2. Once setup, I enabled the GTEsupport feature flag and the notification appears but on top of it the Additional permissions required popup appears. 

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/227254923-7b8ca73f-f31a-46f7-9c5d-54d8f33a29ec.png)

![image](https://user-images.githubusercontent.com/12189958/227257970-ecfb2136-01e4-4f59-b159-97d2a16b2ad7.png)

Video: https://www.loom.com/share/85d68d3602054bc58e0f2df1e525b95b

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Seems like the same issue that was fixed in #5497 🤔

**Comment by aaemnnosttv** [comment]
@jimmymadon the problem is that `GoogleTagIDMismatchNotification` is only rendered if `gteSupport` is enabled. We should also make it conditional based on the scope it requires to prevent invoking the modal to begin with. We also might want to add more conditions to when the scope is returned in `get_scopes` for GA4 but it seems like the previous change solve the main issue here.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
@wpdarren I'm still getting additional permissions pop up. Can you please verify if you also getting it.

**Steps-**

- Created new instaWP site.
- gteSupport featured flag is disabled.
- Set up Site Kit with Analytics.
- Enabled gteSupport feature flag.
- Additional permission pop up appears.

cc @techanvil 

![image](https://user-images.githubusercontent.com/94359491/229117215-bc04d733-0d97-4679-b11f-0bfd3e29e684.png)

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@mohitwp @techanvil yes, I still see the `Additional Permissions Required` on the `develop` branch. 

![image](https://user-images.githubusercontent.com/73545194/229136926-99b060a1-5475-47bd-8367-b74203595b24.png)

I'm sending this back to Execution.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@aaemnnosttv Now Additional permission pop up not appearing when we enabled `gteSupport `feature flag. But I've noticed that when we enable `ga4reporting` feature flag then for first time Additional permission popup appears. After that if I refresh the main dashboard or disbaled and again enabled the '`ga4Reporting` feature flag then pop up is not appearing. 

Should I create a new ticket for this ?

<details>


https://user-images.githubusercontent.com/94359491/229162676-7948c1cf-9a5f-4c21-871e-31f160afc3e7.mp4

</details>

**Comment by aaemnnosttv** [comment]
Hmm, yes, let's address this in a new issue. This is more of a follow up to #6421.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Now 'Additional Permission popup' not showing when we enable 'gteSupport' feature flag.
- For the issue reported [above](https://github.com/google/site-kit-wp/issues/6764#issuecomment-1492119196) I created a new issue -https://github.com/google/site-kit-wp/issues/6806
