### ISSUE TITLE
An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7009]
## Bug Description

A couple of users in the support forum reported the following error :
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')`

We don't have the Site Health information from either user at this point, troubleshooting ongoing. One user did state the error no longer occurred after refreshing the page. Based on the full errors (below) this seems to occur on the main WordPress dashboard:

<details> 
<summary>Stack trace and error - user one</summary>

```
An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'isGA4DashboardView')
at Object.current (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-wp-dashboard-a39ff88870d0d0a0e5e9.js:58:2269)
at e (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:412134)
at https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:412241
at Ii (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:735601)
at Ji (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:735704)
at Sj (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:753648)
at t.unstable_runWithPriority (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:772969)
at Hr (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:697428)
at Jj (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:750120)
at wa (https://XXXXXXXX.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-134c6e6e324fdd7d5926.js:7:746274)

Original stack trace:
in WPDashboardWidgets
in div
in WPDashboardApp
in RestoreSnapshots
in ErrorHandler
in ThemeProvider
in StrictMode
in Root
o
```
 </details> 

<details> 
<summary>Stack trace and error - user two</summary>

```
An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')

The error may be correlated with this previous error:

TypeError: Cannot read properties of null (reading 'isGA4DashboardView')

    at Object.current (https://digitalworldcity.in/wp-content/litespeed/js/0a30a8a69a126443599f621174c2bcc9.js?ver=2bcc9:1:89872)

    at e (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:542145)

    at https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:542252

    at Ii (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:865612)

    at Ji (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:865715)

    at Sj (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:883663)

    at t.unstable_runWithPriority (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:902986)

    at Hr (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:827439)

    at Jj (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:880133)

    at wa (https://digitalworldcity.in/wp-content/litespeed/js/226248304ba392d529bfef0bb0a1ab57.js?ver=1ab57:1:876285)

Original stack trace:

    in AdminBarWidgets

    in div

    in Cell

    in div

    in Row

    in div

    in Grid

    in AdminBarApp

    in RestoreSnapshots

    in ErrorHandler

    in ThemeProvider

    in StrictMode

    in Root
```

 </details> 

- https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect-15 | Open | No SH info
- https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect-14 | Open | No SH info

## Steps to reproduce

Unreproducible so far at support level

## Screenshots

No screenshots thus far

## Additional Context

 - On the one site where we have the site URL, they're using SK 1.99.0. The GA output shows both a UA and a GA4 snippet, without a Google tag ID. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WP dashboard widgets app should not crash if Analytics is not available, nor should errors be shown in the widget
* In this case, only Search Console widgets should be visible

## Implementation Brief

* The issue happens when javascript on the frontend is additionally minified via plugin, causing this line to throw weird error https://github.com/google/site-kit-wp/blob/f5b7620c5a71997deae3639ca1523dc425c5e5fb/assets/js/components/SourceLink.js#L49 Which keeps `analytics` store `undefined` even modules is detected as active and available, which results in `isGA4DashboardView` selector throwing the error.
* Since `GA4` view will be the only available one, after feature flag removal in [#6856](https://github.com/google/site-kit-wp/issues/6856), remove this selector entirely https://github.com/google/site-kit-wp/blob/b80ce4ea163e041e4ae54c2b1d20bb07e369e10e/assets/js/modules/analytics/datastore/settings.js#L294
* Remove it's usage, and where it is used to conditionally render components/markup, return only the ones that would be used if `isGA4DashboardView` is true. At the time of writing, it is used in:
  * `assets/js/modules/analytics/datastore/base.js`
  * `assets/js/components/adminbar/AdminBarWidgets.js`
  * `assets/js/components/notifications/SwitchedToGA4Banner.js`
  * `assets/js/components/notifications/ZeroDataStateNotifications/GatheringDataNotification.js`
  * `assets/js/components/notifications/ZeroDataStateNotifications/index.js`
  * `assets/js/components/wp-dashboard/WPDashboardWidgets.js`
  * `assets/js/googlesitekit/datastore/user/permissions.js`
  * `assets/js/googlesitekit/modules/datastore/modules.js`
  * `assets/js/modules/adsense/index.js`
  * `assets/js/modules/analytics/index.js`
  * `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Footer.js`
  * `assets/js/modules/analytics/datastore/notifications.js`
  * `assets/js/modules/search-console/index.js`
  * `assets/js/modules/search-console/components/common/AnalyticsStats.js`
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Footer.js`
* Remove `isGA4DashboardView` if found anywhere else

### Test Coverage

* No changes needed

## QA Brief
This fix will prevent current error when js is minified with plugins (not guaranteed for all plugins and they can break different things when doing minifications). Solution is tested with plugin that one of the users mentioned in the support forums. Usage with js compiled for production build (dev bundle includes additional webpack references which will break the minifications), will properly portray the fix.

As a solution, applied fix is removing one of the function related to checking between GA4 and UA view, and which was connected to the minified issue. So besides the checks for described bug, be on a lookup for any regression, especially when it comes to Analytics 4 modules and widgets. 

* Setup Site Kit
* Install `Speed Optimizer - The All-In-One WordPress Performance-Boosting Plugin`
* Enable javascript minify option from `Site Optimizer -> Frontend -> Javascript`
* On homepage for example, hover over `Sitekit` top bar menu
* Verify there is no error showing in the dropdown
* Go through Site Kit dashboard and check for any issue, ensure that all widgets are working properly
* Go through WordPress dashboard and ensure Site kit widgets are working properly
* Check general connect/disconnect/reset of Analytics module

## Changelog entry

* Remove non-GA4 dashboard view.

**Comment by jamesozzie** [comment]
An additional user jumped onto [an existing support topic](https://wordpress.org/support/topic/site-kit-link-keeps-expiring/#post-16718936
) mentioning they're encountering the same. They [shared their SH info,](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjK_5i7QXh1tpGp50GWmSmj9xnxKVs756tECTiKsII2RYXVcIo8FbWIgGFXC-FRU9Y) although not referencing their own topic. Troubleshooting ongoing.

**Comment by jamesozzie** [comment]
One additional report of this error, with this impacted user possibly facing this on the front end only in the admin toolbar, based on a Siteground Optimizer plugin. Troubleshooting ongoing. 
https://wordpress.org/support/topic/site-kit-error-on-web-page/#post-16775936

<details><summary>Console Errors</summary>

```
An error occurred while running 'mapSelect': undefined is not an object (evaluating 'a(q.h).isGA4DashboardView')
The error may be correlated with this previous error:
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-adminbar.min.js:1:88008
a@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:531665

@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:531775
he@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:851808
hw@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:851913
ip@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:869551

ip@[native code]
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:888628
al@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:866072
dz@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:862342

dz@[native code]
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:814346
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:888628
eV@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:814293
I@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:814231
ab@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:859005
gp@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:831116

gp@[native code]

a@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:531739
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:531825

forEach@[native code]

g@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:622129
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:619409
g@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:611205
e@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:612741

some@[native code]

b@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:890818
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:890768
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:612699

some@[native code]

b@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:890818
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:890768
g@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:890867
e@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:891119

Promise@[native code]

@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:612825
l@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:747550
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:747303
C@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:608910
d@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609113
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609172

Promise@[native code]

@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609064
l@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:747550
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:747303
C@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:608910
d@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609113
@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609172

Promise@[native code]

@https://beanleaf.co.uk/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:609064
```

</details>

**Comment by aaemnnosttv** [comment]
I found this can happen if the Analytics module's JS is blocked or unable to load for whatever reason. One example in a linked support topic is manipulation/combination by a caching plugin.

This could also happen if Analytics isn't available as a registered module although support for this has always been a bit incomplete. Will move this forward 👍

**Comment by zutigrm** [comment]
Note for execution: I added QA brief, to include steps on how to reproduce this

**Comment by tofumatt** [comment]
It seems part of the issue is that we're calling `select( MODULES_ANALYTICS ).isGA4DashboardView()` without verifying that it's available yet.

It seems something like:

```js
const analyticsModuleAvailable = useSelect( ( select ) =>
	select( CORE_MODULES ).isModuleAvailable( 'analytics' )
);
const analyticsModuleConnected = useSelect( ( select ) =>
	select( CORE_MODULES ).isModuleConnected( 'analytics' )
);
const analyticsModuleActive = useSelect( ( select ) =>
	select( CORE_MODULES ).isModuleActive( 'analytics' )
);
const isGA4DashboardView = useSelect(
  (select) =>
    analyticsModuleAvailable &&
    analyticsModuleActive &&
    select(MODULES_ANALYTICS).isGA4DashboardView()
);
```

could also work.

But using optional chaining works here I think, so IB ✅

**Comment by aaemnnosttv** [comment]
> * The issue happens when javascript on the frontend is additionally minified via plugin, causing this line to throw weird error

This can affect any Analytics selector used from a "core" bundle – in this case, the errors are from the WP Dashboard and Admin Bar apps. This can also happen if the Analytics module is not available, e.g. via `googlesitekit_available_modules` filter.

About this error specifically, we should use this issue to remove this selector since it should always return true now (SK won't show the UA interface anymore), although I think this issue is probably blocked by #6856.

Sending back to IB (sorry @tofumatt !)

**Comment by zutigrm** [comment]
@aaemnnosttv Thank you for the feedback. 
Should we open a more general issue, to address lack of checks for module availability in core modules store selectors?

**Comment by aaemnnosttv** [comment]
> Should we open a more general issue, to address lack of checks for module availability in core modules store selectors?

@zutigrm It would be good to do an audit of sorts, I took a look at this recently and there weren't too many instances I don't think (at least that caused errors for GA). Core selectors shouldn't rely on module stores in general – this is more about the few apps that integrate different modules directly rather than using the widgets API, for example. This was intentional in the past but does require more checks that we don't have elsewhere because of the kind of decoupled nature. I think it would be good to move to a more consistent application but that may be more effort than is reasonable to spend right now.

All that to say, feel free to open an additional issue if there isn't one already 👍 

--

Regarding the IB, I was suggesting that we remove this selector entirely. It goes beyond the specific error reported here, but that's okay. If anything, it would ensure this error is indeed solved because the underlying selector would no longer exist 😄

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm – LGTM! Just a note regarding the QAB, this is for the author of the PR to complete. We should also be careful about setting expectations that SK should be compatible with various optimization plugins because they can do all kinds of things to break things for us 😄 

IB ✅

**Comment by aaemnnosttv** [comment]
@zutigrm please amend the QAB to highlight the larger changes made here

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm 

I created 2 sites.

**Site 1** : Set up on site kit an latest environment. Installed speed optimizer and enabled minify javascript files. I can see error on Homepage when I hover over Sitekit top bar menu. Switched to develop environment and still error appearing on develop environment.

![image](https://github.com/google/site-kit-wp/assets/94359491/8da9bdb8-4df9-4a60-b427-4a676fe4de70)

**Site 2** : Set up site kit on develop environment. Installed speed optimizer and enabled minify javascript files. Error is not showing in front end when I hover over Sitekit top bar menu. 

**Question** : - As i can see this fix is working for only newly created site but not for old sites. Is this expected ?

![image](https://github.com/google/site-kit-wp/assets/94359491/6ae417f6-c5bc-4427-8cc9-1a7c59bb36f5)


**Question 2** : On Site 2 on develop map selecte error is not showing. But getting couple of console errors. Is this expected ?

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3bd02db2-f0f9-4f50-8005-ac9d0f318c08)

![image](https://github.com/google/site-kit-wp/assets/94359491/a34d256b-7e3a-4d5b-bec5-becd5d61c4b3)

</details>

**Comment by zutigrm** [comment]
@mohitwp Thanks for checking this. As I can see on the first site, the error that is shown is regarding the `isGA4DashbaordView` which was removed from the codebase, so it seems you are seeing the cached version of javascript. The behaviour on site 2 is the expected on after the change.

I would suggest, for the site 1, switching the branch from `develop` to, lets say `latest` for example, and then back to `develop` to pull the latest codebase, this should resolve the cache issue. And also clear the cache from the speed optimizer plugin options.

**Comment by mohitwp** [comment]
@zutigrm 

Switched from dev to latest and back to dev. Purge catch multiple times during this whole process but map select error is still showing.


https://github.com/google/site-kit-wp/assets/94359491/83a49067-223a-4867-9b48-dfa0f8ba9fdf

**Comment by zutigrm** [comment]
@mohitwp It seems the `develop` is not pulling in the latest code changes, since that piece of code throwing the error is not present anymore. Perhaps trying to force the update, or removing/installing it again, might pull the latest codebase

**Comment by mohitwp** [comment]
### QA Update ❌ 

@zutigrm I tested on main environment after main is updated. But getting the same error as reported above.

- Tested on main environment.
**Steps -**

- **Site 1** : Set up on site kit an latest environment. Installed speed optimizer and enabled minify javascript files. I can see error on Homepage when I hover over Sitekit top bar menu. Switched to main environment and still error appearing on main environment.
- 
- Switched between dev, main and latest multiple times. Also, purged speed optimizer and browser cache but error is still showing

See attached screencast

```
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'isGA4DashboardView')
    at Object.current (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-adminbar.min.js:2:6743)
    at e (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:309717)
    at https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:309824
    at Ii (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:851783)
    at Ji (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:851886)
    at Sj (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:869834)
    at t.unstable_runWithPriority (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:889157)
    at Br (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:813610)
    at Jj (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:866304)
    at wa (https://ignorantthumb.s3-tastewp.com/wp-content/uploads/siteground-optimizer-assets/googlesitekit-vendor.min.js:1:862456)

Original stack trace:

    in AdminBarWidgets
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in AdminBarApp
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`
```

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/42cbc5e8-413f-45ed-970f-84ff9dce661f)


https://github.com/google/site-kit-wp/assets/94359491/dd36c055-647d-46b7-a369-10de98597822

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment with Speed Optimizer plugin.
- Not sure what was the issue before but issue reported above is now resolved.
- Now after switching from latest to main environment 'Map select' errors gets remove from Site kit bar in front end.
- Also, verified GA4 dashboard widgets functionality on SK dashboard and on WP dashboard. 
- Verified site kit set up and disconnect functionality. All functionalities are working as expected
- Verified for old site created on latest environment and having speed optimizer plugin. 
- Also, for new site created on dev environment. 

<details>


https://github.com/google/site-kit-wp/assets/94359491/1efb9c42-2580-4288-a876-eb2a7a712650


https://github.com/google/site-kit-wp/assets/94359491/1f1c67f3-c01e-4d4b-8bd5-da6284eebdba


</details>
