### ISSUE TITLE
Settings has 'Enable groups' CTA instead of toggle

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9366]
## Bug Description

This was raised while testing https://github.com/google/site-kit-wp/issues/8577

- When we click on 'Settings' to deactivate this widget on a second admin, it brings up the 'Enable groups' button. 
- By right, I would expect the toggle only at this point so that it can be turned on and off.  You may refer to the 1m40 mark on the video below.

## Steps to reproduce

- Set up Site Kit with the audienceSegmentation feature flag enabled, and click on Enable groups to set the feature up.
- Archive all of the audiences for the connected property barring "All Users".
- Login as a second admin user and connect Site Kit. The second admin should have view access or higher for the connected property.
- The banner copy says 
   - 'You don't have any visitor groups selected. [Select groups]
   - You can deactivate this widget in [Settings]
- WHen clicking on 'Settings', you go to the settings but instead of having the toggle to turn it on or off, there is the 'Enable groups' CTA. (You may refer to the 1m40 mark on the video below)

## Screenshots

https://github.com/user-attachments/assets/3b6b7d84-2c20-4af4-bcb9-9fd5975c610f

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Having run through the **steps to reproduce**, the **Display visitor groups in dashboard** toggle should appear in the Settings section, and the **Enable groups** CTA should not be present.
* Additionally:
  * For the primary admin, having dismissed the Setup CTA on the dashboard, the **Enable groups** CTA should still be present in the Settings section.
  * For a secondary admin, if the user lands on the Settings screen before having visited the dashboard to allow their audiences to be auto-selected, the **Enable groups** CTA should _not_ be present, and the **Display visitor groups in dashboard** toggle should appear instead.

## Implementation Brief

* In `SettingsCardVisitorGroups`:
  * [x] Retrieve `audienceSegmentationSetupCompletedBy` and return `null` while it is `undefined`.
  * [x] Update the conditional rendering so that the `SetupCTA` is rendered when `configuredAudiences` is truthy and `audienceSegmentationSetupCompletedBy` is `null`, rather than testing `configuredAudiences.length`. I.e. the condition should be `! configuredAudiences && audienceSegmentationSetupCompletedBy === null`. Render the `SetupSuccess` and `Switch` fragment when the inverse is true.
https://github.com/google/site-kit-wp/blob/40f5363b0a49a3c24126d76b44e20cd1c22e919f/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/index.js#L74-L75
* [x] In `SettingsCardVisitorGroups/SetupCTA`, remove the conditional rendering of `null`  when the `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION` item is dismissed:
https://github.com/google/site-kit-wp/blob/c8f046917554e9883108545cb864ea20647ab9ba/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupCTA.js#L46-L54

### Test Coverage

* Fix failing JS and VRT tests.

## QA Brief

* Follow the **steps to reproduce** as outlined to verify that:
    * The "Display visitor groups in dashboard" toggle appears in the Settings section when a second admin user is logged in.
    * The "Enable groups" CTA should not be present in the Settings section for this admin.
* **Primary admin**: After dismissing the Setup CTA on the dashboard, ensure that the "Enable groups" CTA remains in the Settings section.
* **Secondary admin**: 
    * If the secondary admin visits the Settings page before visiting the dashboard (to allow audiences to be auto-selected), verify that the "Enable groups" CTA does not appear. 
    * Instead, the "Display visitor groups in dashboard" toggle should be displayed.

## Changelog entry

* Fix conditions for showing the "Enable groups" and "Display visitor groups in dashboard" toggle on the Settings screen.

**Comment by nfmohit** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @nfmohit, following @hussain-t's [question on Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1726830706201089) I've realised a couple of additional related fixes should be addressed here, so I've updated the AC and IB accordingly.

Please can you give the IB another review?

**Comment by nfmohit** [comment]
Thank you @techanvil! Updated IB 👍 ✅

**Comment by techanvil** [comment]
Hi @hussain-t, the PR looks good, but the QAB could be a bit confusing as the **steps to reproduce** are really quite specific to the first AC point; the aspects relating to archiving audiences are irrelevant to the additional AC points.

Please can you amend the QAB to help clarify this?

**Comment by techanvil** [comment]
Thanks @hussain-t, I see your thumbs up on the above comment. I've merged the PR and assigned this to you in QA to make the update to the QAB.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've updated the QAB. Please let me know if it looks good.

**Comment by techanvil** [comment]
Thanks @hussain-t! That LGTM, cheers.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- For the primary admin, having dismissed the Setup CTA on the dashboard, the Enable groups CTA is still present in the Settings section.
   <Details>
   
   https://github.com/user-attachments/assets/0d801ac9-2772-473a-9bdb-696c522a81b8

   </Details>

- For a secondary admin, if the user lands on the Settings screen before having visited the dashboard to allow their audiences to be auto-selected, the Enable groups CTA is not present, and the Display visitor groups in dashboard toggle appears instead

   <Details>
  
   https://github.com/user-attachments/assets/db157834-6bb8-41a9-baf2-4fdc2577e182

   </Details>
